### ISSUE TITLE
Unsupported CPU architecture: x86_64 (linux-musl)

### ISSUE THREAD

**Issue by azzamsa** [dprint/dprint-plugin-prettier#60]
Hi.

The plugin fails in the `ubuntu-22.04` CI but works locally.

```yml
jobs:
  code_quality:
    name: Code quality
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - uses: taiki-e/install-action@dprint

      - name: Show version information
        shell: bash
        run: |
          dprint --version

      - name: Ensure `fmt` has been run
        run:  dprint check
```

```
Run dprint --version
dprint 0.41.0
2s

Run dprint check
  dprint check
  shell: /usr/bin/bash -e {0}
Compiling https://plugins.dprint.dev/markdown-0.16.2.wasm
Compiling https://plugins.dprint.dev/toml-0.5.4.wasm
Error resolving plugin https://plugins.dprint.dev/prettier-0.27.0.json: Unsupported CPU architecture: x86_64 (linux-musl)
Error: Process completed with exit code 12.
```

But it works locally.

```
Fedora Linux 38 (Workstation Edition)

🙊 dprint --version
dprint 0.41.0
```
